
(in-package #:cl-user)

(defpackage :cl-mach
  (:nicknames :mach)
  (:use :cl :cffi :hurd-common)
  (:export :port
           :task
           :vm-size
           :vm-address
           :msg-option
           :ipc-space
           :port-mscount
           :port-seqno
           :msg-seqno
           :port-delta
           :msg-type-number
           :msg-type-name
           :vm-offset
           :msg-size
           :msg-timeout
           :vm-task
           :port-urefs
           :port-msgcount
           :port-rights
           :msg-bits
           :msg-id
           :task-self
           :with-port-deallocate
           :with-port-destroy
           :with-port
           :port-type-is-p
           :port-pointer
           :port-valid-p
           :port-allocate
           :port-deallocate
           :port-destroy
           :port-mod-refs
           :port-move-member
           :port-insert-right
           :port-type
           :port-request-notification
           :task-get-special-port
           :task-get-bootstrap-port
           :msg-server-timeout
           :msg-server
           :mmap-prot-flags
           :mmap-map-flags
           :mmap
           :munmap
           :vm-allocate
           :vm-deallocate
           :reply-port
           :port-allocate-name
           :port-names
           :port-rename
           :port-get-refs
           :port-extract-right
           :port-set-mscount
           :port-set-qlimit
           :+qlimit-default+
           :+qlimit-min+
           :+qlimit-max+
           :port-set-seqno
           :port-get-set-status
           :port-get-receive-status
           :port-status-has-send-rights-p
           :port-status-has-port-deleted-notification-p
           :port-status-has-no-senders-notification-p
           :port-status-get-set
           :port-status-get-mscount
           :port-status-get-queue-limit
           :port-status-get-msgcount
           :port-status-get-so-rights
           :msg-add-type
           :message-spec
           :message
           :msg-spec
           :msg-fields
           :spec-id
           :spec-fields
           :spec-size
           :send-message
           :receive-message
           :validate-message
           :get-message
           :get-message-id
           :get-message-local-port
           :get-message-remote-port
           :make-message
           :make-message-spec))

