
(in-package #:cl-user)

(defpackage :cl-hurd
  (:nicknames :hurd)
  (:use :cl :cffi :mach :hurd-common :tg)
  (:export :auth-getids
           :exec-exec
           :exec-flags
           :getauth
           :get-send-right
           :get-right
           :port-right
           :fsys-startup
           :fsys-getroot
           :bucket
           :make-bucket
           :run-server
           :bucket-add-port
           :bucket-add-control-port
           :bucket-has-port-p
           :bucket-lookup-port
           :+servers+
           :+servers-exec+
           :+servers-crash+
           :+servers-proc+
           :+servers-password+
           :+servers-socket+
           :+hurd+
           :+hurd-init+
           :+hurd-proc+
           :+hurd-auth+
           :+hurd-symlink+
           :+hurd-chrdev+
           :+hurd-blkdev+
           :+hurd-fifo+
           :+hurd-ifsock+
           :file-name-lookup
           :dir-readdir
           :dir-link
           :dir-lookup
           :dir-mkdir
           :dir-mkfile
           :dir-rename
           :dir-rmdir
           :dir-unlink
           :file-chauthor
           :file-check-access
           :file-chmod
           :file-chown
           :file-get-fs-options
           :file-get-translator-cntl
           :file-get-translator
           :file-getcontrol
           :file-getlinknode
           :file-lock-stat
           :file-lock
           :file-reparent
           :file-set-size
           :file-set-translator
           :file-statfs
           :file-sync
           :file-syncfs
           :file-utimes
           :fsys-get-options
           :fsys-goaway
           :fsys-syncfs
           :fsys-set-options
           :io-server-version
           :io-duplicate
           :io-get-owner
           :io-identity
           :io-mod-owner
           :io-set-all-openmodes
           :io-get-openmodes
           :io-set-some-openmodes
           :io-clear-some-openmodes
           :io-pathconf
           :io-read
           :io-stat
           :io-readable
           :io-restrict-auth
           :io-revoke
           :io-seek
           :io-select
           :io-write
           :get-privileged-ports
           :getcrdir
           :getcttyid
           :getcwdir
           :geteuids
           :getproc
           :getumask
           :pid2task
           :setauth
           :setcttyid
           :setcwdir
           :seteuids
           :setproc
           :task2pid
           :make-iouser
           :make-iouser-mem
           :make-iouser-root
           :make-empty-iouser
           :contains-uid-p
           :contains-gid-p
           :empty-uids-p
           :empty-gids-p
           :restrict-iouser
           :iouser
           :retry-type
           :box-active-p
           :box-passive-p
           :box-translated-p
           :passive
           :make-transbox
           :port-info
           :define-hurd-interface
           :notify-server
           :fetch-root
           :auth-t
           :fsys-t
           :io-t
           :process-t
           :socket-t
           :pf-t
           :addr-port-t
           :startup-t
           :fs-notify-t
           :proccoll-t
           :is-controller-p
           :has-access-p
           :can-modify-dir-p
           :is-owner-p
           :box-drop
           :box-set-active
           :box-set-passive
           :fsys-goaway-flags
           :fsys-goaway-reply
           :bucket-count-type
           :bucket-count
           :bucket-iterate
           :bucket-find
           :bucket-remove-port
           :deallocate-send-right
           :user-reauth
           :get-io-identity
           :fs-trans-flags
           :box-fetch-control
           :file-storage-class
           :transbox
           :+honored-open-modes+
           :+honored-get-modes+
           :make-translator-options
           :get-translator-options
           :has-translator-option-p
           :get-translator-option
           :set-translator-options
           :get-foreign-options
           :translator-options
           :add-option
           :iterate-options
           :exec-reauth
           :port-cleanup))

