
(load "translator/interfaces/fsys-getroot")
(load "translator/interfaces/io-stat")
(load "translator/interfaces/file-chmod")
(load "translator/interfaces/file-chown")
(load "translator/interfaces/file-utimes")
(load "translator/interfaces/io-pathconf")
(load "translator/interfaces/io-server-version")
(load "translator/interfaces/dir-lookup")
(load "translator/interfaces/dir-readdir")
(load "translator/interfaces/file-chauthor")
(load "translator/interfaces/io-mod-owner")
(load "translator/interfaces/dir-mkdir")
(load "translator/interfaces/dir-unlink")
(load "translator/interfaces/dir-rmdir")
(load "translator/interfaces/io-read")
(load "translator/interfaces/file-sync")
(load "translator/interfaces/io-get-openmodes")
(load "translator/interfaces/io-get-owner")
(load "translator/interfaces/io-set-some-openmodes")
(load "translator/interfaces/io-set-all-openmodes")
(load "translator/interfaces/file-getlinknode")
(load "translator/interfaces/file-syncfs")
(load "translator/interfaces/io-duplicate")
(load "translator/interfaces/io-clear-some-openmodes")
(load "translator/interfaces/io-readable")

