
(in-package #:cl-user)

(defpackage :cl-hurd.translator
  (:nicknames :hurd-translator)
  (:use :cl :cffi :mach :hurd-common
        :hurd :tg :flexi-streams)
  (:export :fs-server
           :io-server
           :fsys-server
           :translator
           :make-root-node
           :pathconf
           :allow-open-p
           :node
           :chmod-file
           :chown-file
           :utimes-file
           :directory-lookup
           :create-file
           :number-of-entries
           :get-entries
           :allow-author-change-p
           :create-directory
           :remove-directory-entry
           :read-file
           :write-file
           :run-translator
           :define-callback
           :make-translator
           :sync-file
           :sync-fs
           :drop-node
           :make-node-dirent
           :report-access
           :refresh-statfs
           :*translator*
           :get-statfs
           :file-change-size
           :file-rename
           :shutdown
           :create-anonymous-file
           :create-hard-link
           :block-read
           :block-write
           :set-options
           :options-changed
           :create-symlink
           :link
           :allow-link-p
           :options
           :create-block
           :create-character
           :create-fifo
           :create-socket
           :storage
           :refresh-node
           :underlying-node
           :version
           :root
           :+auth-server+
           :+exec-server+
           :show-tables
           :def-io-interface
           :def-fs-interface
           :def-fsys-interface
           :stack-servers
           :with-lookup
           :port-bucket
           :identity-port
           :owner
           :stat
           :box
           :open-node
           :refers
           :file-offset
           :lock-status
           :flags
           :root-parent
           :shadow-root
           :shadow-root-parent
           :make-open-node
           :install-shadow-root
           :protid
           :make-protid
           :get-stat
           :get-box
           :get-node
           :get-user
           :get-shadow-root
           :get-shadow-root-parent
           :get-root-parent
           :get-open-flags
           :open-node
           :user
           :translator-demuxer
           :node-transbox
           :port-exists-p))

