(in-package :hurd-translator)

(load "translator/globals")
(load "translator/io_wrapper")
(load "translator/fs_wrapper")
(load "translator/fsys_wrapper")
(load "translator/macros")
(load "translator/debug")
(load "translator/demuxer")
(load "translator/node")
(load "translator/open")
(load "translator/protid")
(load "translator/utils")
(load "translator/class")
(load "translator/api")
(load "translator/dirent")
(load "translator/interfaces/interfaces")
(load "translator/run")
