
(in-package :hurd)

(defcfun ("exec_exec" exec-exec)
  err
  (execserver port)
  (file port)
  (file-type msg-type-name)
  (oldtask task)
  (flags exec-flags)
  (argv :pointer)
  (argvlen msg-type-number)
  (envp :pointer)
  (envplen msg-type-number)
  (dtable :pointer)
  (dtable-type msg-type-name)
  (dtablelen msg-type-number)
  (portarray :pointer)
  (portarray-type msg-type-name)
  (portarraylen msg-type-number)
  (intarray :pointer)
  (intarraylen msg-type-number)
  (deallocnames :pointer)
  (deallocnameslen msg-type-number)
  (destroynames :pointer)
  (destroynameslen msg-type-number))

